language: node_js

node_js:
  - 'node'

sudo: required

cache:
  yarn: true

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
