language: node_js

node_js:
  - "node"

sudo: true

cache:
  directories:
    - "node_modules"

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
